cephadm: adjust downstream `docker.io` count
3a8be57779ca26fb203a2ae618d356616a9e1ab5 introduced a count of all
occurances of `docker.io` when flake8 is run. Adjust this count to
reflect the number of occurances expected downstream

```
flake8 run-test: commands[1] | bash -c 'test $(git ls-files cephadm | grep ".py$" | grep -v tests | xargs grep "docker.io" | wc -l) == 13'
ERROR: InvocationError for command /usr/bin/bash -c 'test $(git ls-files cephadm | grep ".py$" | grep -v tests | xargs grep "docker.io" | wc -l) == 13' (exited with code 1)
```

Signed-off-by: Michael Fritch <mfritch@suse.com>